### PR TITLE
Lambda govcloud backend

### PR DESCRIPTION
**Pull request by djkiourtsis**
Boto does not include govcloud when listing lambda regions.  In order to test with a govcloud region, it must be added manually.

### CODE REVIEW

**Comment by djkiourtsis** [comment]
[Users should be able to change the instance type of a running instance](https://trello.com/c/5uD6QaHn/2484-users-should-be-able-to-change-the-instance-type-of-a-running-instance)

**Comment by djkiourtsis** [comment]
[Local test runner and travis are posting to AWS.](https://trello.com/c/tZtYmcwa/2526-local-test-runner-and-travis-are-posting-to-aws)

**Comment by mliudev** [comment]
Did you ever make a pull request upstream to include this change?

**Comment by mliudev** [comment]
This has been merged upstream already.

**Pull request closed without merging**
